services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Headless\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Headless\Json\JsonEncoder:
    public: true
